export const API = "https://qbhf2c9996.execute-api.us-east-1.amazonaws.com/dev"
export const PRODUCTS_ENDPOINT = "products"
export const PRODUCT_ENDPOINT = "product"
export const PHONE_NUMBER = "+5519993955537"
export const PAGE_BASE = "https://master.do9fyga9tdb2l.amplifyapp.com"
export const PAGE_TITLE = "Atelie Cris Silva"
export const PAGE_DESCRIPTION = "Loja virtual do Atelie Cris Silva"
